<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <PublishAot>True</PublishAot>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\..\CSharp Shared\AnsiHelper.cs" Link="Shared\AnsiHelper.cs" />
    <Compile Include="..\..\..\CSharp Shared\Crc32CAlgorithm.cs" Link="Shared\Crc32CAlgorithm.cs" />
    <Compile Include="..\..\..\CSharp Shared\IniReader.cs" Link="Shared\IniReader.cs" />
    <Compile Include="..\FilesUpdaterLib\ConsoleHelper.cs" Link="Shared\ConsoleHelper.cs" />
    <Compile Include="..\FilesUpdaterLib\Helper\Hasher.cs" Link="Shared\Hasher.cs" />
    <Compile Include="..\FilesUpdaterLib\Helper\Utils.cs" Link="Shared\Utils.cs" />
    <Compile Include="..\FilesUpdaterLib\Structures\ConfigStructure.cs" Link="Shared\ConfigStructure.cs" />
    <Compile Include="..\FilesUpdaterLib\Structures\UserConfigStruct.cs" Link="Shared\UserConfigStruct.cs" />
    <Compile Include="..\FilesUpdaterLib\XorStream.cs" Link="Shared\XorStream.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="9.0.8" />
    <PackageReference Include="ZstdSharp.Port" Version="0.8.6" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Shared\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FilesUpdaterLib\FilesUpdaterLib.csproj" />
  </ItemGroup>

</Project>
