<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <LangVersion>preview</LangVersion>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>FilesUpdaterLib</RootNamespace>
    <EnforceCodeStyleInBuild>False</EnforceCodeStyleInBuild>
    <EnableNETAnalyzers>True</EnableNETAnalyzers>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\..\CSharp Shared\AnsiHelper.cs" Link="Helper\AnsiHelper.cs" />
    <Compile Include="..\..\..\CSharp Shared\Crc32CAlgorithm.cs" Link="Helper\Crc32CAlgorithm.cs" />
    <Compile Include="..\..\..\CSharp Shared\IniReader.cs" Link="Helper\IniReader.cs" />
  </ItemGroup>

</Project>
